name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Download and Install Clang 21.0.0
        run: |
          wget https://github.com/ZyCromerZ/Clang/releases/download/21.0.0git-20250225-release/Clang-21.0.0.tar.gz
          tar -xf Clang-21.0.0.tar.gz
          sudo mv Clang-21.0.0 /usr/local/clang-21.0
          echo "/usr/local/clang-21.0/bin" >> $GITHUB_PATH

      - name: Build Kernel
        uses: ElGabrielx7/kernel_build_action@main
        with:
          kernel-url: https://github.com/ElGabrielx7/not_r8q_ui.git
          kernel-branch: interstellar
          config: not_defconfig
          arch: arm64
          aosp-gcc: false  # Mantendo desativado para evitar erro do GCC ausente
          aosp-clang: false  # Desativado para evitar conflito com Clang 21.0.0
