name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Baixar Clang 21
      run: |
        mkdir -p ~/clang-21
        wget https://github.com/ZyCromerZ/Clang/releases/download/21.0.0git-20250225-release/Clang-21.0.0git-20250225.tar.gz
        tar -xf Clang-21.0.0git-20250225.tar.gz -C ~/clang-21 --strip-components=1
        echo "CLANG_PATH=$HOME/clang-21" >> $GITHUB_ENV

    - name: Build Kernel
      uses: ElGabrielx7/kernel_build_action@main
      with:
          kernel-url: https://github.com/ElGabrielx7/Gabrielx7-android_kernel_samsung_sm8250.git
          kernel-dir: interstellar
          kernel-branch: interstellar
          config: not_defconfig
          arch: arm64
          aosp-clang: false
          other-clang-url: ${{ env.CLANG_PATH }}
          ksu: true
          kvm: true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-artifacts
        path: anykernel3/*.zip
