name: Build kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Download and Install Clang 19.1.0
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.0/clang+llvm-19.1.0-aarch64-linux-gnu.tar.xz
        tar -xf clang+llvm-19.1.0-aarch64-linux-gnu.tar.xz
        sudo mv clang+llvm-19.1.0-aarch64-linux-gnu /usr/local/clang-19.1

    - name: Set up Clang 19.1.0
      run: |
        echo "/usr/local/clang-19.1/bin" >> $GITHUB_PATH
        echo "/usr/local/clang-19.1/lib" >> $GITHUB_LIB_PATH

    - name: Build
      uses: ElGabrielx7/kernel_build_action@main
      with:
        kernel-url: https://github.com/ElGabrielx7/not_r8q_ui.git
        kernel-branch: interstellar
        config: not_defconfig
        arch: arm64
        aosp-gcc: true
        aosp-clang: false
