name: Build kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: ElGabrielx7/kernel_build_action@main
        with:
          kernel-url: https://github.com/ElGabrielx7/not_r8q_ui.git
          kernel-branch: interstellar
          config: not_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r522817
